name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Lint
        uses: astral-sh/ruff-action@v3
        with:
          src: ./weather_app

      - name: Check formatting
        uses: astral-sh/ruff-action@v3
        with:
          src: ./weather_app
          args: format --check

  test-and-build:
    runs-on: ubuntu-latest
    needs: lint-and-format

    env:
      IMAGE_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/weather-app

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Test
        uses: docker/build-push-action@v6
        with:
          push: false
          target: tests
          tags: ${{ env.IMAGE_TAG }}-test

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.IMAGE_TAG }}:${{ github.sha }}
